"""empty message

Revision ID: 16d05a88d18a
Revises: 6e074a0a7756
Create Date: 2021-01-22 00:00:03.208480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d05a88d18a'
down_revision = '6e074a0a7756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component_element', 'component_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component_element', sa.Column('component_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
