"""empty message

Revision ID: 23b0c966357d
Revises: 16d05a88d18a
Create Date: 2021-01-22 00:16:46.826052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b0c966357d'
down_revision = '16d05a88d18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_component_associations',
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['page_component.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], )
    )
    op.create_foreign_key(None, 'page', 'page_category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_table('page_component_associations')
    # ### end Alembic commands ###
