"""empty message

Revision ID: 3301975294dc
Revises: b10cd6a4a2c9
Create Date: 2021-01-21 23:47:28.628465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3301975294dc'
down_revision = 'b10cd6a4a2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component_element', sa.Column('component_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component_element', 'component_type')
    # ### end Alembic commands ###
