"""empty message

Revision ID: 5dfe5e34c378
Revises: 49ecb023f7c8
Create Date: 2021-01-18 15:00:12.142786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfe5e34c378'
down_revision = '49ecb023f7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image')
    # ### end Alembic commands ###
