"""empty message

Revision ID: 60e7633b4236
Revises: 23b0c966357d
Create Date: 2021-01-25 12:48:56.828386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e7633b4236'
down_revision = '23b0c966357d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component_element', sa.Column('value', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component_element', 'value')
    # ### end Alembic commands ###
