"""empty message

Revision ID: 6521ba9a2912
Revises: 73904aa785a2
Create Date: 2021-01-31 22:25:26.176174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6521ba9a2912'
down_revision = '73904aa785a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v3__section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('edited_on', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=9999), nullable=True),
    sa.Column('thumbnail', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thumbnail'], ['v3__image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v3__section')
    # ### end Alembic commands ###
