"""empty message

Revision ID: 6e074a0a7756
Revises: 3301975294dc
Create Date: 2021-01-21 23:59:23.608085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e074a0a7756'
down_revision = '3301975294dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_element_associations',
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['page_component.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['component_element.id'], )
    )
    op.add_column('page_component', sa.Column('component_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_component', 'component_type')
    op.drop_table('component_element_associations')
    # ### end Alembic commands ###
