"""empty message

Revision ID: 70ffe7cf1c7e
Revises: 6521ba9a2912
Create Date: 2021-01-31 22:35:11.882362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ffe7cf1c7e'
down_revision = '6521ba9a2912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v3_article_sections',
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['v3__article.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['v3__section.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v3_article_sections')
    # ### end Alembic commands ###
