"""empty message

Revision ID: 73904aa785a2
Revises: 6aa5a52de032
Create Date: 2021-01-31 11:55:27.270197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73904aa785a2'
down_revision = '6aa5a52de032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v3__article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('edited_on', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=3000), nullable=True),
    sa.Column('lead', sa.String(length=250), nullable=True),
    sa.Column('thumbnail', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thumbnail'], ['v3__image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v3__article')
    # ### end Alembic commands ###
