"""empty message

Revision ID: ad73e72a62f4
Revises: eb6b0155021d
Create Date: 2021-01-16 16:31:19.056477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad73e72a62f4'
down_revision = 'eb6b0155021d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_edit', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_edit')
    # ### end Alembic commands ###
