"""empty message

Revision ID: b10cd6a4a2c9
Revises: b3ea5197c875
Create Date: 2021-01-21 21:34:09.881450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10cd6a4a2c9'
down_revision = 'b3ea5197c875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component_element', sa.Column('element_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component_element', 'element_type')
    # ### end Alembic commands ###
