"""empty message

Revision ID: c56d4b6386e6
Revises: aaac6acd1279
Create Date: 2021-01-30 15:29:31.908365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56d4b6386e6'
down_revision = 'aaac6acd1279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v3_navbar_links',
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('navbar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['v3__link.id'], ),
    sa.ForeignKeyConstraint(['navbar_id'], ['v3__navbar.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v3_navbar_links')
    # ### end Alembic commands ###
